[package]
name = "aconfig_protos"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
default = ["cargo"]
cargo = []

[dependencies]
anyhow = "1.0.69"
paste = "1.0.11"
protobuf = "3.2.0"

[build-dependencies]
protobuf-codegen = "3.2.0"
