[package]
name = "aflags"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
paste = "1.0.11"
clap = { version = "4", features = ["derive"] }
protobuf = "3.2.0"
regex = "1.10.3"
aconfig_protos = { path = "../aconfig_protos" }
